export CUDA_VISIBLE_DEVICES=2
dataset=cifar10

python3 main_pretrain.py \
    --dataset ${dataset} \
    --backbone vit_base \
    --train_data_path ./datasets \
    --val_data_path ./datasets \
    --max_epochs 1000 \
    --devices 0 \
    --accelerator gpu \
    --precision 16 \
    --optimizer adamw \
    --scheduler warmup_cosine \
    --lr 0.005 \
    --warmup_start_lr 1e-6 \
    --classifier_lr 3e-3 \
    --weight_decay 1e-4 \
    --batch_size 64 \
    --num_workers 5 \
    --brightness 0.4 \
    --contrast 0.4 \
    --saturation 0.2 \
    --hue 0.1 \
    --gaussian_prob 0.0 0.0 \
    --solarization_prob 0.0 0.2 \
    --crop_size 32 \
    --num_crops_per_aug 1 1 \
    --name dino-${dataset}-vit-baseline \
    --entity jmeng15 \
    --project iclr2023_sparse_ssl \
    --wandb \
    --save_checkpoint \
    --auto_resume \
    --method dino \
    --proj_output_dim 256 \
    --proj_hidden_dim 2048 \
    --num_prototypes 4096 \
    --base_tau_momentum 0.9995 \
    --final_tau_momentum 1.0 \
    --momentum_classifier
