python3 main_linear.py \
    --dataset imagenet100 \
    --backbone mobilenetv2 \
    --train_data_path /home/jmeng15/data/imagenet-100/train \
    --val_data_path /home/jmeng15/data/imagenet-100/val \
    --max_epochs 100 \
    --devices 1 \
    --accelerator gpu \
    --precision 16 \
    --optimizer sgd \
    --scheduler step \
    --lr 3.0 \
    --lr_decay_steps 60 80 \
    --weight_decay 0 \
    --batch_size 256 \
    --num_workers 10 \
    --data_format dali \
    --name mocov2plus-mobilenetv2-imagenet100-linear-eval \
    --pretrained_feature_extractor /home/jmeng15/solo-learn-sparse/trained_models/mocov2plus/21d9qrmx/mocov2plus-400ep-mobilenetv2_1x-21d9qrmx-ep=399.ckpt \
    --entity jmeng15 \
    --project light-ssl \
    --wandb \
    --save_checkpoint \
    --auto_resume
