python3 main_linear.py \
    --dataset imagenet100 \
    --backbone mobilenetv2 \
    --train_data_path /home2/jmeng15/data/imagenet-100/train \
    --val_data_path /home2/jmeng15/data/imagenet-100/val \
    --max_epochs 100 \
    --devices 0 \
    --accelerator gpu \
    --precision 16 \
    --optimizer sgd \
    --scheduler step \
    --lr 1.0 \
    --lr_decay_steps 60 80 \
    --weight_decay 0 \
    --batch_size 256 \
    --num_workers 10 \
    --data_format dali \
    --name simclr-mobilenetv2-imagenet100-linear-eval \
    --pretrained_feature_extractor /home2/jmeng15/solo-learn-sparse/trained_models/simclr/7bw6batz/simclr-400ep-imagenet100-mobilenetv2_1x-7bw6batz-ep=399.ckpt \
    --entity jmeng15 \
    --project light-ssl \
    --wandb \
    --save_checkpoint \
    --auto_resume
