export CUDA_VISIBLE_DEVICES=0,2,3

python3 main_pretrain.py \
    --dataset imagenet100 \
    --backbone mobilenetv1_2x \
    --train_data_path /home/jmeng15/data/imagenet-100/train \
    --val_data_path /home/jmeng15/data/imagenet-100/val \
    --max_epochs 400 \
    --devices 0,1,2 \
    --accelerator gpu \
    --strategy ddp \
    --sync_batchnorm \
    --precision 16 \
    --optimizer lars \
    --grad_clip_lars \
    --eta_lars 0.02 \
    --exclude_bias_n_norm_lars \
    --scheduler warmup_cosine \
    --lr 0.3 \
    --weight_decay 1e-4 \
    --batch_size 128 \
    --num_workers 4 \
    --brightness 0.8 \
    --contrast 0.8 \
    --saturation 0.8 \
    --hue 0.2 \
    --num_crops_per_aug 2 \
    --name simclr-400ep-imagenet100-mobilenetv1_1.25x \
    --data_format dali \
    --entity jmeng15 \
    --project light-ssl \
    --wandb \
    --save_checkpoint \
    --method simclr \
    --temperature 0.2 \
    --proj_hidden_dim 2048
